language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
env:
  - APP_CONFIG_FILE=travis
script: travis_retry python manage.py test
addons:
  sauce_connect: true
deploy:
  provider: heroku
  api_key:
    secure: fJILYiNWa31jfeIEo/v05AyEaLKh9ziJ3UZRGFDmyeqtp3ko82lAAkod6WlBxAHqtJpzAnTafZjjZ6cS3Wwq1FkQDhe5iqH/0Qo8B7U6yx3TDb9j5tVH7oYxE81qkGCDDGLSgzET18gRB3+Adw+X84sqEGmt1xxHStA+Edsk5gU=
  app: sourcemash-staging
  run:
    - "python manage.py assets build"
    - "python manage.py db upgrade"