language: python
cache: pip
sudo: false
python:
- '2.7'
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - APP_CONFIG_FILE=travis
script: python manage.py test
after_success:
  - coveralls
  - openssl aes-256-cbc -k '' -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa \
  - bash ./scripts/dokku_deploy.sh
deploy:
  provider: heroku
  api_key:
    secure: DMvNpEN//RAhkq3WzQs8NMAbINmTnoYqEVq4QCESblMmss6hiA90miUDajgOtF/UiDtf9vdsxK1szq6YaH99PWj41S+O7qneL1eCtFH2+kiQufyMDJ4TQ4Nw4Ope0aOb1jDyubuUf61TfWLXSzr1o/HLyCODYJVuWHm247/lJUY=
  app:
    master: sourcemash-staging
  run:
    - "python manage.py assets clean"
    - "python manage.py assets build"
    - "python manage.py db upgrade"
